table moedas
	lineageTag: 3ff66c7c-f0a2-4d40-8798-6169de1f0031

	column Moeda
		dataType: string
		lineageTag: 693a01c4-bebb-41a2-97f3-30729e90d536
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: 8ee23b85-e3ab-4ec3-adf2-bb43cd82538e
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Formato
		dataType: string
		lineageTag: d6d283d5-72d4-4ba7-b2e4-cf2c6448ed24
		summarizeBy: none
		sourceColumn: Formato

		annotation SummarizationSetBy = Automatic

	partition moedas = m
		mode: import
		queryGroup: Dimensoes
		source = ```
				let
				    source = Table.FromRows(
				        {
				            {"BRL", "Real brasileiro", "R$ #,##0.00;R$ #,##0.00;-"},
				            {"AUD", "Dólar australiano", "$ #,##0.00;$ #,##0.00;-"},
				            {"CAD", "Dólar canadense", "$ #,##0.00;$ #,##0.00;-"},
				            {"CHF", "Franco suíço", "Fr #,##0.00;Fr #,##0.00;-"},
				            {"DKK", "Coroa dinamarquesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"EUR", "Euro", "€ #,##0.00;€ #,##0.00;-"},
				            {"GBP", "Libra Esterlina", "£ #,##0.00;£ #,##0.00;-"},
				            {"JPY", "Iene", "¥ #,##0;¥ #,##0;-"},
				            {"NOK", "Coroa norueguesa", "kr #,##0.00;kr #,##0.00;-"},
				            {"SEK", "Coroa sueca", "kr #,##0.00;kr #,##0.00;-"},
				            {"USD", "Dólar dos Estados Unidos", "$ #,##0.00;$ #,##0.00;-"}
				        },
				        {"Moeda", "Nome", "Formato"}
				    ),
				    
				    changedType = Table.TransformColumnTypes(
				        source,{
				            {"Moeda", type text}, 
				            {"Nome", type text}, 
				            {"Formato", type text}
				        }
				    )
				
				in
				    changedType
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

